# Version of docker-compose
version: '3.2'

# Containers we are going to run
services:
  # Our Phoenix container
  phoenix:
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      # Variables to connect to our Postgres server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thepostgrespassword
      POSTGRES_DB: easypodcasts_dev
      PGHOST: db
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      # The db container needs to be started before we start this container
      - db
    command:
      - ./docker/run.sh
  db:
    # We use the predefined Postgres image
    image: postgres:12.0-alpine
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thepostgrespassword
      POSTGRES_DB: easypodcasts_dev
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata: